const projectData = [
  {
    id: 1,
    projectName: "Spadex Tools",
    images: [
      "/project/project1/spadexToolThumbnail.PNG",
      "/project/project1/spadex_3.PNG",
      "/project/project1/spadex_2.PNG",
      "/project/project1/spadex_4.PNG",
    ],
    features: [
      "Login authentication with firebase also use google sign in.",
      "Fully responsive, Home page has navbar, banner, All tools, Business Summary, Review overview, contact and footer section.",
      "User and Admin different Dashboard",
      "User can update profile info, place order and add a review also can payment with credit card",
      "Admin can make admin, cancel and shipped order, Add product and manage products",
    ],
    technologies: [
      "React JS",
      "Tailwind CSS",
      "Daisyui",
      "Firebase",
      "React Router",
      "React Query",
      "React Toastify",
      "React hook form",
      "React Firebase Hooks",
      "Font Awesome icon",
      "Stripe payment",
      "Mongodb",
      "Express JS",
      "Node JS",
      "JSON Web Token",
    ],
    links: {
      liveSite: "https://manufacture-website-e2667.web.app/",
      clientSource:
        "https://github.com/motalibpathan/manufacturer-website-client",
      serverSource:
        "https://github.com/motalibpathan/manufacturer-website-server",
    },
  },
  {
    id: 2,
    projectName: "Car Max",
    images: [
      "/project/project2/carMax.PNG",
      "/project/project2/carMax_2.PNG",
      "/project/project2/carMax_3.PNG",
      "/project/project2/carMax_4.PNG",
    ],
    features: [
      "In Home page displayed 6 inventories (car) with some information like image, title, short description, price and quantity and a button for stock update.",
      "The stock update button navigate the inventory page here also some information of clicked inventory and has a button delivered. Delivered button will reduce quantity 1. Also has a input box and a button for add quantity.",
      "In Manage Inventory page displayed all inventories and has a delete button for delete and manage button for manage quantities.",
      "In Add Inventory page user can add inventory",
      "In my inventory page displaying the current user added inventories.",
      "User can sigup using email and password, also can signin using google singin method",
    ],
    technologies: [
      "React JS",
      "Tailwind CSS",
      "Firebase",
      "React Router",
      "React Toastify",
      "React Firebase Hooks",
      "Font Awesome icon",
      "Mongodb",
      "Express JS",
      "Node JS",
      "JSON Web Token",
    ],
    links: {
      liveSite: "https://warehouse-management-85499.web.app/",
      clientSource:
        "https://github.com/motalibpathan/warehouse-management-client",
      serverSource:
        "https://github.com/motalibpathan/warehouse-management-server",
    },
  },
  {
    id: 3,
    projectName: "Red Onion",
    images: [
      "/project/project3/RedOnion.PNG",
      "/project/project3/redOnion_2.PNG",
      "/project/project3/redOnion_3.PNG",
      "/project/project3/redOnion_4.PNG",
    ],
    features: [
      "Login authentication with firebase also use google sign in.",
      "Fully responsive, Home page has navbar, banner, Food Menu, About Section",
      "User can add items to cart",
      "Cart to place order",
      "User order route for view orders",
    ],
    technologies: [
      "React JS",
      "Tailwind CSS",
      "Firebase",
      "React Router",
      "React Toastify",
      "React Firebase Hooks",
      "Font Awesome icon",
      "Mongodb",
      "Express JS",
      "Node JS",
      "JSON Web Token",
    ],
    links: {
      liveSite: "https://red-onion-eight.vercel.app/",
      clientSource: "https://github.com/motalibpathan/red-onion",
      serverSource: "https://github.com/motalibpathan/red-onion-server",
    },
  },
  {
    id: 4,
    projectName: "Eric Photography",
    images: [
      "/project/project4/ericPhotography.PNG",
      "/project/project4/ericPhotography_2.PNG",
      "/project/project4/ericPhotography_3.PNG",
      "/project/project4/ericPhotography_4.PNG",
    ],
    features: [
      "This is a photographer service website.",
      "This website has Navbar, slider, Service and Footer section in Home page.",
      "It has also Login page and sign up page.",
      "User can also sing in with google account.",
      "Checkout page is protected route, user can not go this route without login.",
    ],
    technologies: [
      "React JS",
      "Tailwind CSS",
      "Firebase",
      "React Router",
      "React Toastify",
      "React Firebase Hooks",
      "Font Awesome icon",
    ],
    links: {
      liveSite: "https://eric-photography.web.app/",
      clientSource:
        "https://github.com/motalibpathan/photography-service-provider",
      serverSource: "",
    },
  },
  {
    id: 5,
    projectName: "Dashboard Project",
    images: [
      "/project/project5/salesTracker.PNG",
      "/project/project5/salesTracker_2.PNG",
      "/project/project5/salesTracker_3.PNG",
      "/project/project5/salesTracker_4.PNG",
      "/project/project5/salesTracker_5.PNG",
    ],
    features: [
      "Login authentication with firebase also use google sign in.",
      "Inventory sales tracker and calculate profit",
      "User can add product and update product quantities",
      "Can track sell and generate invoice and anytime can view invoice",
      "Can manage items, low stock items and stock out items",
    ],
    technologies: [
      "React JS",
      "Tailwind CSS",
      "Firebase",
      "React Router",
      "React Toastify",
      "Firebase Realtime Database",
      "Font Awesome",
      "Serverless",
      "Animated Number React",
      "React Type Animation",
    ],
    links: {
      liveSite: "https://sales-tracket-with-react.vercel.app/",
      clientSource: "https://github.com/motalibpathan/sales-tracker-with-react",
      serverSource: "",
    },
  },
  {
    id: 6,
    projectName: "Laptop Review ",
    images: [
      "/project/project6/laptopReview.PNG",
      "/project/project6/laptopReview_2.PNG",
      "/project/project6/laptopReview_3.PNG",
    ],
    features: [
      "This is a simple product review website",
      "This website is created with React Js Library. For displaying chart I have used 'recharts'",
      "User and Admin different Dashboard",
      "This website has been used React Router V6.",
      "In Home page showing a product and some reviews, in Reviews page showing all reviews.",
    ],
    technologies: [
      "React JS",
      "Bootstrap",
      "JavaScript",
      "ES6",
      "Font Awesome",
      "Recharts",
    ],
    links: {
      liveSite: "https://laptop-review-motalibpathan.netlify.app/",
      clientSource: "https://github.com/motalibpathan/laptop-review-react",
      serverSource: "",
    },
  },
];

export default projectData;
